# Configuration API REST pour TaskForce
api_platform:
  title: 'TaskForce API'
  version: '1.0.0'
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
    html: ['text/html']
  docs_formats:
    jsonld: ['application/ld+json']
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']
  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
    extra_properties: false
    pagination_client_enabled: true
    pagination_items_per_page: 30
    pagination_maximum_items_per_page: 100
  collection:
    pagination:
      enabled: true
      items_per_page: 30
      maximum_items_per_page: 100
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
