# Configuration Symfony pour TaskForce Backend
# Copier ce fichier vers config/packages/ et adapter selon vos besoins

# Configuration de la base de données
doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver: 'pdo_mysql'
    server_version: '8.0'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App

# Configuration de la sécurité
security:
  enable_authenticator_manager: true
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      jwt: ~
      logout:
        path: app_logout
        target: app_home

# Configuration des routes
framework:
  router:
    default_uri: 'http://localhost'
  secret: '%env(APP_SECRET)%'
  http_method_override: false
  handle_all_throwables: true
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
  php_errors:
    log: true
  mailer:
    dsn: '%env(MAILER_DSN)%'
  notifier:
    transport: '%env(MESSENGER_TRANSPORT_DSN)%'
  messenger:
    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'
      failed: 'doctrine://default?queue_name=failed'
      sync: 'sync://'
    routing:
      App\Message\AsyncMessage: async
    failure_transport: failed

# Configuration des services
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
  
  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
  
  App\Service\:
    resource: '../src/Service/'
    tags: ['app.service']
  
  App\Repository\:
    resource: '../src/Repository/'
    tags: ['app.repository']

# Configuration des logs
monolog:
  channels: ['deprecation']
  handlers:
    main:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
      channels: ['!event']
    deprecation:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.deprecations.log'
      channels: ['deprecation']
